server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sneakcart_auth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: sneakcart-super-secret-key-change-in-production
  expiration: 86400000   # 24 hours in ms
